"""One-shot import of the 'HWY 9 Leaderboard' Google Sheet into leaderboard.db.

Safe to re-run: existing courses and runs are left untouched.
"""

import db

SKIDPAD = {
    "name": "Skidpad to 4 Corners Uphill",
    "distance_miles": 1.65,
    "legacy_distance_miles": 1.7,
}
INTRO = {
    "name": "Intro to HWY 9",
    "distance_miles": None,
    "legacy_distance_miles": None,
}

SKIDPAD_RUNS = [
    (
        "1:18.341",
        350,
        "2001 C5 Corvette",
        78.12,
        110.7,
        "JH",
        "8/7/26",
        "8:00 PM",
        "Dry",
        True,
    ),
    (
        "1:16.634",
        305,
        "2000 Camaro Z28",
        77.51,
        104.5,
        "JH",
        "6/12/26",
        "9:00 PM",
        "Dry",
        False,
    ),
    (
        "1:19.231",
        350,
        "2007 BMW Z4M",
        77.24,
        102.5,
        "RG",
        "5/3/26",
        "7:00 PM",
        "Dry",
        True,
    ),
    (
        "1:22.781",
        166,
        "2006 Honda Accord",
        73.93,
        94.7,
        "RB",
        "4/5/26",
        "11:00 AM",
        "Dry",
        True,
    ),
    (
        "1:24.436",
        250,
        "2023 Mazda 3 Turbo",
        72.48,
        95.7,
        "RG",
        "6/12/25",
        "10:00 PM",
        "Dry",
        True,
    ),
    (
        "1:28.313",
        120,
        "2013 Mini Clubman",
        69.30,
        82.6,
        "SH",
        "6/12/25",
        "10:00 PM",
        "Dry",
        True,
    ),
    (
        "1:28.677",
        205,
        "2015 Mazda 3",
        69.01,
        92,
        "RG",
        "1/25/25",
        "11:00 PM",
        "Dry",
        True,
    ),
    (
        "1:29.570",
        150,
        "1986 Porsche 944",
        68.33,
        84,
        "GM",
        "11/30/25",
        "7:00 PM",
        "Dry",
        True,
    ),
    (
        "1:30.325",
        135,
        "1996 Mazda Miata",
        67.76,
        87.3,
        "IB",
        "2/17/25",
        "7:00 PM",
        "Dry",
        True,
    ),
    (
        "1:30.533",
        180,
        "2014 Mini Cooper S",
        67.60,
        86.7,
        "CA",
        "7/19/26",
        "11:00 AM",
        "Dry",
        True,
    ),
    (
        "1:27.966",
        155,
        "2017 Mazda Miata RF GT",
        67.53,
        88.8,
        "RB",
        "8/7/26",
        "8:00 PM",
        "Dry",
        False,
    ),
    (
        "1:20.805",
        155,
        "2017 Mazda Miata RF GT",
        73.51,
        95.9,
        "IB",
        "8/29/26",
        "7:00 PM",
        "Dry",
        False,
    ),
    (
        "1:31.369",
        360,
        "2019 BMW 440i",
        66.98,
        93.2,
        "A",
        "4/10/25",
        "10:00 PM",
        "Dry",
        True,
    ),
    (
        "1:31.563",
        368,
        "2018 Kia Stinger",
        66.84,
        94.3,
        "K",
        "2/14/25",
        "9:00 PM",
        "Wet",
        True,
    ),
    (
        "1:34.689",
        220,
        "2003 VW GTI",
        64.63,
        84,
        "GM",
        "2/28/26",
        "11:00 PM",
        "Dry",
        True,
    ),
    (
        "1:34.777",
        350,
        "1966 Ford Mustang",
        64.57,
        79.6,
        "CM",
        "5/7/26",
        "8:00 PM",
        "Dry",
        True,
    ),
    (
        "1:39.889",
        271,
        "1963 Austin Healy",
        61.27,
        81.9,
        "IB",
        "2/22/25",
        "1:00 PM",
        "Dry",
        True,
    ),
    (
        "1:40.059",
        181,
        "1995 Jeep Grand Cherokee",
        61.16,
        81.2,
        "JH",
        "4/27/26",
        "9:00 PM",
        "Dry",
        True,
    ),
    (
        "1:40.922",
        205,
        "2015 Mazda 3",
        60.64,
        81.8,
        "SH",
        "1/25/25",
        "11:00 PM",
        "Dry",
        True,
    ),
    (
        "1:45.360",
        400,
        "2018 Mustang Ecoboost",
        58.09,
        88.6,
        "BS",
        "1/26/25",
        "4:00 PM",
        "Dry",
        True,
    ),
    (
        "1:46.709",
        110,
        "2010 Honda Civic Hybrid",
        57.35,
        72.5,
        "RO",
        "4/5/26",
        "11:00 AM",
        "Dry",
        True,
    ),
    (
        "1:47.110",
        175,
        "2025 Chevy Malibu",
        57.14,
        85.5,
        "RG",
        "1/29/25",
        "10:00 PM",
        "Dry",
        True,
    ),
    (
        "1:56.980",
        127,
        "2001 Honda Civic",
        50.78,
        64.5,
        "RJ",
        "6/7/26",
        "7:00 PM",
        "Dry",
        False,
    ),
]

INTRO_RUNS = [
    (
        "3:01.271",
        205,
        "2015 Mazda 3",
        54.6,
        80.8,
        "RG",
        "1/18/25",
        "9:00 PM",
        "Dry",
        "NB",
    ),
    (
        "3:04.323",
        250,
        "2023 Mazda 3 Turbo",
        53.1,
        84,
        "RG",
        "3/7/25",
        "11:00 PM",
        "Dry",
        "NB",
    ),
    (
        "3:05.41",
        121,
        "2013 Mini Clubman",
        52.9,
        74.3,
        "SH",
        "3/6/25",
        "8:00 PM",
        "Wet",
        "SB",
    ),
    (
        "3:10.485",
        305,
        "2000 Camaro Z28",
        52.4,
        73.7,
        "JH",
        "1/18/25",
        "9:00 PM",
        "Dry",
        "NB",
    ),
    (
        "3:11.558",
        175,
        "2025 Chevy Malibu",
        51.4,
        79.2,
        "RG",
        "1/29/25",
        "9:00 PM",
        "Dry",
        "NB",
    ),
    (
        "3:43.565",
        175,
        "2024 GMC Terrain",
        44,
        67.1,
        "RG",
        "1/27/25",
        "10:00 PM",
        "Dry",
        "NB",
    ),
    (
        "3:53.669",
        360,
        "2019 BMW 440i",
        42.4,
        72.2,
        "A",
        "3/12/25",
        "9:00 PM",
        "Wet",
        "NB",
    ),
    (
        "4:53.977",
        119,
        "1980s BMW 528e",
        35.5,
        50.1,
        "IB",
        "1/18/25",
        "4:00 PM",
        "Dry",
        "NB",
    ),
]


def iso_date(us_date: str) -> str:
    month, day, year = us_date.split("/")
    return f"20{year}-{int(month):02d}-{int(day):02d}"


def ensure_course(conn, course: dict) -> int:
    row = conn.execute(
        "SELECT id FROM courses WHERE name = ?", (course["name"],)
    ).fetchone()
    if row:
        return row["id"]
    cur = conn.execute(
        "INSERT INTO courses (name, distance_miles, legacy_distance_miles) VALUES (?, ?, ?)",
        (course["name"], course["distance_miles"], course["legacy_distance_miles"]),
    )
    return cur.lastrowid


def insert_run(
    conn,
    course_id,
    time,
    hp,
    vehicle,
    avg,
    top,
    driver,
    date,
    tod,
    conditions,
    legacy,
    notes,
):
    seconds = db.parse_time(time)
    run_date = iso_date(date)
    exists = conn.execute(
        "SELECT 1 FROM runs WHERE course_id = ? AND driver = ? AND time_seconds = ? AND run_date = ?",
        (course_id, driver, seconds, run_date),
    ).fetchone()
    if exists:
        return False
    conn.execute(
        """INSERT INTO runs (course_id, driver, vehicle, hp, time_seconds, avg_speed_mph,
            top_speed_mph, run_date, time_of_day, conditions, legacy, notes, source)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'sheet')""",
        (
            course_id,
            driver,
            vehicle,
            hp,
            seconds,
            avg,
            top,
            run_date,
            tod,
            conditions,
            int(legacy),
            notes,
        ),
    )
    return True


def main():
    with db.session() as conn:
        skidpad_id = ensure_course(conn, SKIDPAD)
        intro_id = ensure_course(conn, INTRO)
        added = 0
        for (
            time,
            hp,
            vehicle,
            avg,
            top,
            driver,
            date,
            tod,
            cond,
            legacy,
        ) in SKIDPAD_RUNS:
            added += insert_run(
                conn,
                skidpad_id,
                time,
                hp,
                vehicle,
                avg,
                top,
                driver,
                date,
                tod,
                cond,
                legacy,
                None,
            )
        for (
            time,
            hp,
            vehicle,
            avg,
            top,
            driver,
            date,
            tod,
            cond,
            direction,
        ) in INTRO_RUNS:
            added += insert_run(
                conn,
                intro_id,
                time,
                hp,
                vehicle,
                avg,
                top,
                driver,
                date,
                tod,
                cond,
                False,
                direction,
            )
        total = conn.execute("SELECT COUNT(*) FROM runs").fetchone()[0]
    print(f"Imported {added} new runs ({total} total) into {db.DB_PATH}")


if __name__ == "__main__":
    main()
